cargo/cargo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^tms/', include('tms.urls')),
    url(r'^admin/', admin.site.urls),
]

cargo/tms/urls.py
from django.conf.urls import url
from django.views.generic.base import TemplateView

from tms.vistas import cliGest
from tms.vistas import paiGest
from tms.vistas import secGest

from . import views

app_name = 'tms'

urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^signin/$', views.signin, name='signin'),
        
        
        
        url(r'^cli/$', cliGest.index, name='cli'),
        url(r'^cli/(?P<id>[0-9]+)/$', cliGest.detail, name='cli.edit'),
        
        url(r'^mm/$', views.mm, name='views-mm'),
        
        url(r'^pai/$', paiGest.Index.as_view(), name='pai'),
        url(r'^pai/(?P<paicod>[a-zA-Z0-9]+)/$', paiGest.Edit.as_view(), name='pai.edit'),
        url(r'^paiadd/$', paiGest.Edit.as_view(), name='pai.add'),
        url(r'^paias/$', TemplateView.as_view(template_name='tms/paias.html'), name='pai.as'),
        
        #url(r'^pai/$', paiGest.index, name='pai'),
        #url(r'^pai/(?P<paicod>[a-zA-Z0-9]+)/$', paiGest.edit, name='pai.edit'),
        url(r'^pai/(?P<paicod>[a-zA-Z0-9]+)/save/$', paiGest.save, name='pai.save'),
        
        # ^\S+$
        
        url(r'^sec/$', secGest.index, name='sec'),
        url(r'^sec/(?P<seccod>[a-zA-Z0-9]+)/$', secGest.edit, name='sec.edit'),
        url(r'^sec/(?P<seccod>[a-zA-Z0-9]+)/save/$', secGest.save, name='sec.save'),
        
        url('^home/$', views.HomeView.as_view(), name='home')
        
        
]

cargo/tms/models/BaseBL.py
from .exceptions import OperationNotAllowedException

class BaseBL():

    def _deleteAllowed(self, m):
        return True

    def _preDelete(self, m):
        pass
    
    def _postDelete(self, m):
        pass

    def delete(self, m):
        if not self._deleteAllowed(m):
            raise OperationNotAllowedException(m)
        self._preDelete(m)
        m.save()
        self._postDelete(m)
    
    
    def _insertAllowed(self, m):
        return True

    def _preInsert(self, m):
        pass
    
    def _postInsert(self, m):
        pass

    def insert(self, m):
        if not self._insertAllowed(m):
            raise OperationNotAllowedException(m)
        self._preInsert(m)
        m.save()
        self._postInsert(m)


    def _updateAllowed(self, m):
        return True

    def _preUpdate(self, m):
        pass
    
    def _postUpdate(self, m):
        pass

    def update(self, m):
        if not self._updateAllowed(m):
            raise OperationNotAllowedException(m)
        self._preUpdate(m)
        m.save()
        self._postUpdate(m)

 
        
       

cargo/tms/models/PaiBL.py
from django.db import transaction

from tms.models import Sec
from tms.models.BaseBL import BaseBL
from tms.models.SecBL import SecBL

#from .BaseBL import BaseBL

class PaiBL(BaseBL):
   
    pass

cargo/tms/models/SecBL.py
from django.core.exceptions import ObjectDoesNotExist
from django.db import transaction

from .BaseBL import BaseBL
from tms.models import Sec


class SecBL(BaseBL):

    def next(self, s):
        sid = transaction.savepoint()
        try:
            sec = Sec.objects.get(seccod = s)
        except ObjectDoesNotExist:
            sec = Sec(seccod = s, secval = 0)
            sec.save()
        sec = Sec.objects.get(seccod = s)
        sec.secval += 1
        sec.save()
        transaction.savepoint_commit(sid)
        return sec.secval
            

cargo/tms/models/exceptions.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

class IllegalStateException(RuntimeError):
    def __init__(self, str = ''):
        RuntimeError.__init__(self, str)
        
class OperationNotAllowedException(RuntimeError):
    def __init__(self, str = ''):
        RuntimeError.__init__(self, str)

class UnsupportedOperationException(RuntimeError):
    def __init__(self, str = ''):
        RuntimeError.__init__(self, str)

cargo/tms/models/models.py
import datetime

from django.contrib.gis.db import models
from django.utils.translation import gettext_lazy as _
#
#
#class Question(models.Model):
#    question_text = models.CharField(max_length = 200)
#    pub_date = models.DateTimeField('Date published')
#    
#class Choice(models.Model):
#    question = models.ForeignKey(Question, on_delete = models.CASCADE)
#    choice_text = models.CharField(max_length = 200)
#    votes = models.IntegerField(default = 0)
#    

################################################################################
## SECUENCIAS
class Sec(models.Model):
    version = models.BigIntegerField(default = 0)
    seccod = models.CharField(_('seccod'), max_length = 20, primary_key = True)
    secval = models.BigIntegerField(_('secval'), default = 0)
    secfmt = models.CharField(_('secfmt'), max_length = 20, blank = True)

################################################################################
## VARIABLES INTERNAS
class Vin(models.Model):
    vincod = models.CharField(_('vincod'), max_length = 80, primary_key = True)
    vinalf = models.CharField(_('vinalf'), max_length = 80, blank = True)
    vinnum = models.DecimalField(_('vinnum'), max_digits = 15, decimal_places = 6, 
                                 default = 0)
    vinfec = models.DateField(_('vinfec'), default = datetime.date(1, 1, 1))

################################################################################
## IDIOMAS
class Lng(models.Model):
    lngcod = models.CharField(_('lngcod'), max_length = 2, primary_key = True)
    lngnom = models.CharField(_('lngnom'), max_length = 40, blank = True)
    lngdef = models.BooleanField(_('lngdef'), default = False)
    lngact = models.BooleanField(_('lngact'), default = True)
    
################################################################################
## MONEDAS
class Moa(models.Model):
    moacod = models.CharField(_('moacod'), max_length = 5, primary_key = True)
    moanom = models.CharField(_('moanom'), max_length = 40, blank = True)
    moadec = models.SmallIntegerField(_('moadec'), default = 2)
 
################################################################################
## MONEDAS, TIPO DE CAMBIO
class Mob(models.Model):
    mobcod = models.BigIntegerField(_('mobcod'), default = 0, primary_key = True)
    mobmoacod = models.ForeignKey(Moa, on_delete = models.PROTECT,
                                  db_column = 'mobmoacod')
    mobfec = models.DateField(_('mobfec'), default = datetime.date(1, 1, 1))
    mobrat = models.DecimalField(_('mobrat'), max_digits = 15, decimal_places = 6, 
                                 default = 0)

################################################################################
## ZONAS HORARIAS
class Tzn(models.Model):
    tzncod = models.CharField(_('tzncod'), max_length = 80, primary_key = True)
    tznabr = models.CharField(_('tznabr'), max_length = 5, blank = True)

################################################################################
## PAISES
class Pai(models.Model):
    paicod = models.CharField(_('paicod'), max_length = 2, primary_key = True)
    painom = models.CharField(_('painom'), max_length = 40, blank = True)
    paic3c = models.CharField(_('paic3c'), max_length = 3, blank = True)
    painum = models.SmallIntegerField(_('painum'), default = 0)
    
################################################################################
## ESTADOS
#
# De aplicación solo en aquellos países compuetos por diferentes estados
# como USA, UK, Canadá, etc, donde la dirección no está completa si no se 
# especifica.
#
class Est(models.Model):
    estcod = models.CharField(_('estcod'), max_length = 5, primary_key = True)
    estnom = models.CharField(_('estnom'), max_length = 40, blank = True)
    estpaicod = models.ForeignKey(Pai, on_delete = models.PROTECT,
                               db_column = 'estpaicod')   
    
################################################################################
## POBLACIONES
class Pob(models.Model):
    pobcod = models.BigIntegerField(_('pobcod'), default = 0, primary_key = True)
    pobnom = models.CharField(_('pobnom'), max_length = 80)
    pobpaicod = models.ForeignKey(Pai, on_delete = models.PROTECT,
                                  db_column = 'pobpaicod')
    pobestcod = models.ForeignKey(Est, on_delete = models.PROTECT, 
                                  null = True, 
                                  blank = True,
                                  db_column = 'pobestcod')
    pobtzncod = models.ForeignKey(Tzn, on_delete = models.PROTECT,
                                  db_column = 'pobtzncod')   
    pobloc = models.PointField(_('pobloc'), geography = True, spatial_index = True)
    
################################################################################
## CONCEPTOS DE FACTURACION
#class Cfa(models.Model):
#    cfacod = models.CharField(max_length = 10, primary_key = True)
#    cfanom = models.CharField(max_length = 40)
# 
################################################################################
## CLIENTES
class Cli(models.Model):
    clicod = models.IntegerField(_('clicod'), default = 0, primary_key = True)
    cliextcod = models.CharField(_('cliextcod'), max_length = 20,
                                 blank = True,
                                 db_index = True)
    
    clinom = models.CharField(_('clinom'), max_length = 80, blank = True,
                              db_index = True)
    clinif = models.CharField(_('clinif'), max_length = 20, blank = True,
                              db_index = True)
    clidir = models.CharField(_('clidir'), max_length = 80, blank = True)
    clipcp = models.CharField(_('clipcp'), max_length = 20, blank = True)
    clipob = models.CharField(_('clipob'), max_length = 80, blank = True)
    cliestcod = models.ForeignKey(Est, on_delete = models.PROTECT, 
                                  null = True,
                                  blank = True,
                                  db_column = 'cliestcod')
    clipaicod = models.ForeignKey(Pai, on_delete = models.PROTECT,
                                  db_column = 'clipaicod')
    clitzncod = models.ForeignKey(Tzn, on_delete = models.PROTECT,
                                  db_column = 'pobtzncod')   
    cliloc = models.PointField(_('pobloc'), geography = True,
                               spatial_index = True)
    clitlf = models.CharField(_('clitlf'), max_length = 20, blank = True)
    clifax = models.CharField(_('clifax'), max_length = 20, blank = True)
    clieml = models.EmailField(_('clieml'), blank = True)
    
    climoacod = models.ForeignKey(Moa, on_delete = models.PROTECT,
                                  db_column = 'climoacod')
    
    clida1 = models.CharField(_('clida1'), max_length = 20, blank = True)
    clida2 = models.CharField(_('clida2'), max_length = 20, blank = True)
    clida3 = models.CharField(_('clida3'), max_length = 20, blank = True)
    clida4 = models.CharField(_('clida4'), max_length = 20, blank = True)
#   
################################################################################
## PROVEEDORES
class Pro(models.Model):
    procod = models.IntegerField(_('procod'), default = 0, primary_key = True)
    proextcod = models.CharField(_('proextcod'), max_length = 20, blank = True,
                                 db_index = True)
    
    pronom = models.CharField(_('pronom'), max_length = 80, blank = True, db_index = True)
    pronif = models.CharField(_('pronif'), max_length = 20, blank = True, db_index = True)
    prodir = models.CharField(_('prodir'), max_length = 80, blank = True)
    propcp = models.CharField(_('propcp'), max_length = 20, blank = True)
    propob = models.CharField(_('propob'), max_length = 80, blank = True)
    proestcod = models.ForeignKey(Est, on_delete = models.PROTECT,
                                  null = True,
                                  blank = True,
                                  db_column = 'proestcod')    
    propaicod = models.ForeignKey(Pai, on_delete = models.PROTECT,
                               db_column = 'propaicod')
    protzncod = models.ForeignKey(Tzn, on_delete = models.PROTECT,
                                  db_column = 'pobtzncod')   
    proloc = models.PointField(_('pobloc'), geography = True,
                               spatial_index = True)
    protlf = models.CharField(_('protlf'), max_length = 20, blank = True)
    profax = models.CharField(_('profax'), max_length = 20, blank = True)
    proeml = models.EmailField(_('proeml'), blank = True)  

    promoacod = models.ForeignKey(Moa, on_delete = models.PROTECT,
                                  db_column = 'promoacod')

    proda1 = models.CharField(_('proda1'), max_length = 20, blank = True)
    proda2 = models.CharField(_('proda2'), max_length = 20, blank = True)
    proda3 = models.CharField(_('proda3'), max_length = 20, blank = True)
    proda4 = models.CharField(_('proda4'), max_length = 20, blank = True)
    
################################################################################
## DELEGACIONES
class Del(models.Model):
    delcod = models.CharField(_('delcod'), max_length = 5, primary_key = True)
    
    delnom = models.CharField(_('delnom'), max_length = 80, blank = True, db_index = True)
    deldir = models.CharField(_('deldir'), max_length = 80, blank = True)
    delpcp = models.CharField(_('delpcp'), max_length = 20, blank = True)
    delpob = models.CharField(_('delpob'), max_length = 80, blank = True)
    delestcod = models.ForeignKey(Est, on_delete = models.PROTECT, 
                                  null = True,
                                  blank = True,
                                  db_column = 'delestcod')    
    delpaicod = models.ForeignKey(Pai, on_delete = models.PROTECT,
                                  db_column = 'delpaicod')
    deltzncod = models.ForeignKey(Tzn, on_delete = models.PROTECT,

cargo/tms/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render

from django import forms

from django.views.generic import FormView
from django.views.generic.base import TemplateView

def index(request):
    return render(request, 'tms/index.html')

def signin(request):
    
    username = request.POST['username']
    password = request.POST['password']
    
    print('usuario %s, password %s' % (username, password))
    
    user = authenticate(request=request, username=username, password=password) # compatibilidad 1.10
    if user is not None:
        login(request, user)
        return render(request, 'tms/mm.html')
    else:
        return render(request, 'tms/index.html')
 


def signout(request):
    logout(request)
    return render(request, 'tms/index.html')

def mm(request):
    return render(request, 'tms/mm.html')



    


class HomeView(TemplateView):
    template_name = 'tms/index2.html'
    
    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
#        messages.info(self.request, "hello http://example.com")
        return context

cargo/tms/templates/tms/base.html
<html>{% load i18n %}
<head>
    {% block titulo %}<title>CARGO-TMS</title>{% endblock %}
    {% load static %}

    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'tms/jquery-ui-1.11.4/jquery-ui.css' %}" />    
    <link rel="stylesheet" type="text/css" href="/static/tms/style.css?v=1" />
    
    <script type="text/javascript" src="{% static 'tms/jquery-3.3.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'tms/jquery-ui-1.11.4/jquery-ui.js' %}"></script>
    
</head>
<body class="ui-widget">

{% block cabecera %}{% endblock %}

{% block menu %}{% endblock %}

{% block cont %}{% endblock %}

{% block pie %}{% endblock %}

</body>

cargo/tms/templates/tms/base_edit.html
{% extends "tms/base.html" %}

cargo/tms/templates/tms/base_gest.html
{% extends "tms/base.html" %}

cargo/tms/templates/tms/clis.html
{% if listado %}
    <ul>
    {% for obj in listado %}
        <li><a href="/tms/cli/{{ cli.clicod}}/">{{ cli.clinom }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No hay clientes.</p>
{% endif %}

cargo/tms/templates/tms/index.html
{% extends "tms/base.html" %}

{%block cont %}

<div id="body">

    <div id="login" style="float:left">
        <form method="post" action="/tms/signin/">{% csrf_token %}
            <table class="ui-widget"> 
                <tr>
                    <td>Username:</td><td><input type="text" is="p-inputtext" name="username" size="20"></td>
                </tr>
                <tr>
                    <td>Password:</td><td><input type="password" is="p-password" name="password" size="20" inline="false"></td>
                </tr>
                <tr>
                    <td>&nbsp;</td><td><button is="p-button">Sign in</button></td>
                </tr>
            </table>
        </form>
    </div>

</div>

{% endblock %}

cargo/tms/templates/tms/mm.html
{% extends "tms/base_gest.html" %}

{% block cabecera %} esta es la nueva cabecera {% endblock %}

{% block menu %}

<table>
    <tr>
        <td><a href="{% url 'tms:cli' %}">Clientes</a></td>
        <td><a href="{% url 'tms:pai' %}">Paises</a></td>
        <td><a href="{% url 'tms:sec' %}">Secuencias</a></td>
    </tr>
</table>

{% endblock %}

{% block pie %}



{% endblock %}

cargo/tms/templates/tms/pai.html
<h1>{{pai.paicod}}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action='{%  url 'tms:pai.save' pai.paicod %}' method="post">
    {% csrf_token %}
    <input type="text" id="painom" value="{{ pai.painom }}" />
    <input type="submit" value="Salvar" />
</form>

cargo/tms/templates/tms/paias.html
<form method="get" action="{%  url 'tms:pai' %}">
    {% csrf_token %}
        
    <table>
        <tr>
            <td>Nombre</td>
            <td colspan="2"><input name="q1painom" size="40"/></td>
        </tr>
        <tr>
            <td>Código</td>
            <td><input name="q1paicod" size="5"/></td>
            <td><input name="q2paicod" size="5"/></td>
        </tr>
        <tr>
            <td>Alpha-3</td>
            <td><input name="q1paic3c" size="5"/></td>
            <td><input name="q2paic3c" size="5"/></td>
        </tr>        
        <tr>
            <td>Numérico</td>
            <td><input name="q1painum" size="5"/></td>
            <td><input name="q2painum" size="5"/></td>
        </tr>        
        <tr>
            <td><input type="submit"/></td>
            <td><input type="hidden" name="a" value="s"/></td>
            <td><a href="{% url 'tms:pai' %}">Volver</a></td>
        </tr>        
    </table>    
    
</form>

cargo/tms/templates/tms/pais.html
<!--
<form method="get" action="{%  url 'tms:pai' %}">
    {% csrf_token %}
    <input name="q0paicod" value="pepito"/><input name="q0painom"/><input type="submit"/>
</form>
-->

<style>
    td.align-right {
        text-align : right;
    }
</style>

<form method="get" action="{%  url 'tms:pai' %}">
    {% csrf_token %}
    
    <table>
        <tr>
            <td colspan="99">
                <div style="float:left"><a href="{% url 'tms:pai.add' %}">Crear</a>&nbsp;</div>
                <div style="float:left"><a href="{% url 'tms:pai.as' %}">Buscar</a>&nbsp;</div>
                <div style="float:left"><a href="{% url 'tms:pai' %}?page=1">Primera</a>&nbsp;</div>
                <div style="float:left"><a href="{% url 'tms:pai' %}?page={{ paginator.previous_page_number }}">Anterior</a>&nbsp;</div>
                <div style="float:left"><a href="{% url 'tms:pai' %}?page={{ paginator.next_page_number }}">Siguiente</a>&nbsp;</div>
                <div style="float:left"><a href="{% url 'tms:pai' %}?page=last">Última ({{ paginator.num_pages }})</a>&nbsp;</div>
            </td>
        </tr>
        <tr>
            <td>Alpha2</td>
            <td>Nombre</td>
            <td>Alpha3</td>
            <td>Num</td>
        </tr>
        <tr>
            <td><input name="q0paicod" size="5"/></td>
            <td><input name="q0painom" size="40"/></td>
            <td><input name="q0paic3c" size="5"/></td>
            <td><input name="q0painum" size="5"/></td>
            <td><input type="submit"/></td>
            <td><input type="hidden" name="a" value="s"/></td>
        </tr>        
    {% for obj in object_list %}
        <tr>
            <td><a href="{% url 'tms:pai.edit' obj.paicod %}">{{ obj.paicod }}</a></td>
            <td>{{ obj.painom }}</td>
            <td>{{ obj.paic3c }}</td>
            <td class="align-right">{{ obj.painum }}</td>
        </tr>
    {% endfor %}       
    </table>    
    
</form>

cargo/tms/templates/tms/sec.html
{% extends "tms/base_edit.html" %}

{% block cont %}

<h1>{{ obj.seccod }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'tms:sec.save' obj.seccod %}" method="post">
    {% csrf_token %}
    {{ form }}
    <!--
    <table>
        <tr><td><input name="seccod" value="{{ obj.seccod }}" /></td></tr>
        <tr><td><input name="secval" value="{{ obj.secval }}" /></td></tr>
        <tr><td><input name="secfmt" value="{{ obj.secfmt }}" /></td></tr>
    </table>
    -->
<input type="submit" value="Submit" />
</form>

{% endblock %}

cargo/tms/templates/tms/secs.html
{% if listado %}
    <ul>
    {% for obj in listado %}
        <!--<li><a href="/tms/sec/{{obj.seccod}}">{{ obj.secval }}</a></li>-->
        <li><a href="{% url 'tms:sec.edit' obj.seccod %}">{{ obj.secval }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No hay secuencias.</p>
{% endif %}